Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Actinocatenispora	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Paenisporosarcina	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae	2.1742722203			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Exiguobacterium	1.14961753202			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae	1.01763255894			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Ureibacillus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Brucellaceae.Ochrobactrum	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Paralactobacillus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Cardiobacteriales.Cardiobacteriaceae.Suttonella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Curvibacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Anaerostipes	0.518431576538	Low_O2	2.27709186823	0.00160691102896
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Arthrobacter	0.106473154092			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Kingella	1.68124168207			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Elizabethkingia	0.0			-
Bacteria.Bacteria_incertae_sedis.Ktedonobacteria.Ktedonobacterales.Ktedonobacteraceae	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae	3.26505050664			-
Bacteria.Bacteroidetes.Sphingobacteria	1.08588537696			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Cystobacteraceae.Archangium	0.0			-
Bacteria.BRC1.BRC1_genera_incertae_sedis	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Methylococcales.Methylococcaceae.Methylosarcina	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Geobacillus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Sporanaerobacter	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Syntrophobacterales.Syntrophobacteraceae.Desulforhabdus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae	0.102040775728			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Escherichia_Shigella	0.646825648348			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Dokdonella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhodobiaceae.Parvibaculum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermacoccaceae	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidaceae.Bacteroides	3.61386204542	Low_O2	3.30026735669	3.03429396914e-07
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Pasteurella	0.564946229645			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Phyllobacteriaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Polaromonas	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Thermoleophilales.Thermoleophilaceae.Thermoleophilum	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Acetivibrio	0.864328003101			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Bacillus	0.731567269866			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Rhodoplanes	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae.Thermopolyspora	0.0			-
Bacteria.Bacteroidetes	3.8345675439	Low_O2	3.50494978484	7.28882537081e-07
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Acidimicrobiaceae.Ferrithrix	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Alloiococcus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Anaerovibrio	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Papillibacter	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae	3.0923016841	Low_O2	2.74771035844	2.91304680962e-07
Bacteria.Tenericutes.Mollicutes.Mycoplasmatales.Mycoplasmataceae.Mycoplasma	0.552574917975			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Pilibacter	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfomicrobiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Sanguibacteraceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Pseudomonas	1.25495307469			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Empedobacter	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp7	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp6	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp5	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp4	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp3	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp1	0.0			-
Bacteria.Acidobacteria.Holophagae.Holophagales.Holophagaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Corynebacteriaceae	3.19946207178	High_O2	2.8872948434	1.94485200196e-06
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Campylobacteraceae	1.93327137269			-
Bacteria.Proteobacteria.Betaproteobacteria.Nitrosomonadales.Nitrosomonadaceae.Nitrosospira	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast.Bacillariophyta	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingopyxis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Terracoccus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Oxobacter	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp10	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp17	0.0			-
Bacteria.Lentisphaerae.Lentisphaeria	1.00430451213			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Sporolactobacillaceae.Marinococcus	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Prosthecobacter	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci	0.084332956168			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Nitrobacter	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Kurthia	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Butyricicoccus	0.790989807688	Low_O2	2.19213585335	7.55599319769e-05
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Pediococcus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Erythrobacteraceae.Altererythrobacter	0.0			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae.Streptobacillus	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae	2.57951859742			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales	0.0			-
Bacteria.OD1	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Salinimicrobium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Pannonibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Propioniferax	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Naxibacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Acidocella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Diaphorobacter	0.217277000667			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae	0.513550104175			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Catellatospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Asanoa	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Rudanella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Azorhizophilus	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Anaerococcus	1.87126069767			3.65737005238e-06
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Ignavigranum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Brucellaceae.Brucella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Pseudoxanthomonas	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_II.GpIIa	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Rhodococcus	0.181172749763			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales	1.30218185837			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Fusobacteriaceae.Fusobacterium	2.60133254049			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Slackia	0.0			-
Bacteria.Nitrospira.Nitrospira	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae	0.629042104672			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Bogoriellaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales	0.400689564988			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinosynnemataceae.Lentzea	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp22.Gp22	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae	0.940346697769			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Anoxybacillus	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria	1.93733869411			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast.Chlorophyta	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Gordonia	0.66147686448			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Brooklawnia	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales.Deinococcaceae.Deinococcus	0.0			-
Bacteria.SR1	0.0725661919728			-
Bacteria.Cyanobacteria	1.76273928434			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Tetragenococcus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae	0.804428683538			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Actinobacillus	0.942228107026			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cellulomonadaceae.Actinotalea	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Methylibium	0.262962559444			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Leuconostocaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Buttiauxella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Bogoriellaceae.Georgenia	0.0			-
Bacteria.SR1.SR1_genera_incertae_sedis	0.0725661919728			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Acidovorax	0.178243487174			-
Bacteria.Proteobacteria.Gammaproteobacteria.Cardiobacteriales.Cardiobacteriaceae.Cardiobacterium	0.960123679879			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae	0.20082383347			-
Bacteria.Proteobacteria.Gammaproteobacteria.Vibrionales.Vibrionaceae.Vibrio	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Globicatella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Dactylosporangium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Rubellimicrobium	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae	0.0			-
Bacteria.Deinococcus_Thermus	0.529696200331			-
Bacteria.Synergistetes	0.543036074883			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylobacteriaceae.Methylobacterium	0.911191680236			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Gulbenkiania	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Dyadobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Devosia	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Finegoldia	1.30336494883			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Xanthomonas	0.657177428498			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Paracoccus	1.2977144716			-
Bacteria.Chloroflexi.Chloroflexi.Chloroflexales.Chloroflexaceae.Chloroflexus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Providencia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingomonas	0.720196760117			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Niabella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Parasporobacterium	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae	2.87411198448	Low_O2	2.61098533522	6.00232109862e-05
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae	1.2731596163			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Acidimicrobiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Leucobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhizobiaceae.Rhizobium	0.783992372375			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Nannocystaceae.Nannocystis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Knoellia	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Saprospiraceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Polyangiaceae.Byssovorax	0.0			-
Bacteria.Chloroflexi.Chloroflexi	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinosynnemataceae	0.0			-
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingosinicella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Planifilum	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae	2.48818785846			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Balneimonas	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Sediminibacterium	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Alcaligenes	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp4.Gp4	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales.Methylophilaceae.Methylophilus	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Olivibacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Bibersteinia	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Tissierella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Ferruginibacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Salmonella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae.Pleomorphomonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Aurantimonadaceae.Aurantimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Arenimonas	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Kineosporiaceae.Kineococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Lysinibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Oceanobacillus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Skermanella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Oribacterium	1.73419600574			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae	2.01954640923			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Delftia	0.289518385284			-
Bacteria.OP11.OP11_genera_incertae_sedis	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Hydrogenoanaerobacterium	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Streptococcus	3.26498714913			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Gracilibacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Thermobispora	0.0			-
Bacteria.Chlamydiae.Chlamydiae.Chlamydiales	0.0			-
Bacteria.OD1.OD1_genera_incertae_sedis	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Butyricimonas	2.02842948512			-
Bacteria.Proteobacteria.Deltaproteobacteria.Syntrophobacterales	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Kineosporiaceae.Kineosporia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Thauera	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Scardovia	0.0			-
Bacteria.Nitrospira.Nitrospira.Nitrospirales	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bdellovibrionaceae.Bdellovibrio	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Sphingobacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptomycetaceae.Kitasatospora	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Variovorax	0.0			-
Bacteria.Verrucomicrobia.Spartobacteria.Spartobacteria_genera_incertae_sedis	0.0			-
Bacteria.Acidobacteria.Holophagae.Holophagales.Holophagaceae.Holophaga	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Sporomusa	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Aeromonadaceae.Tolumonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Oxalobacter	0.486947431589			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XVIII.Symbiobacterium	0.0			-
Bacteria.Chlamydiae.Chlamydiae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Formivibrio	0.0			-
Bacteria.Thermotogae.Thermotogae.Thermotogales.Thermotogaceae.Thermotoga	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Jannaschia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales	2.19580081373			1.07738470181e-06
Bacteria.Proteobacteria.Alphaproteobacteria.Alphaproteobacteria_incertae_sedis.Geminicoccus	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Parasegetibacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Giesbergeria	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cryptosporangiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dietziaceae	0.718034938178			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Planctomyces	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Rhodocista	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Alkaliphilus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Trichococcus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales	3.82609447041	High_O2	3.52524287296	3.84125180545e-09
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Microlunatus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Hyphomicrobium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Dendrosporobacter	0.0			-
Bacteria.Tenericutes.Mollicutes.Acholeplasmatales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Microbacterium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Dorea	1.25192535646			2.36608609493e-05
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Promicromonosporaceae.Promicromonospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Kineosporiaceae	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae.Helicobacter	0.0			-
Bacteria.Nitrospira.Nitrospira.Nitrospirales.Nitrospiraceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Succinivibrionaceae.Anaerobiospirillum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Yaniellaceae	0.0			-
Bacteria.Thermotogae.Thermotogae	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Granulicatella	1.89555953961			-
Bacteria.Actinobacteria.Actinobacteria.Nitriliruptorales	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Tepidimicrobium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Raoultella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Kibdelosporangium	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_I.GpI	0.0			-
Bacteria.Synergistetes.Synergistia	0.543036074883			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae	1.48534750275			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Mucilaginibacter	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Limnobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Sporotomaculum	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Vibrionales	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Erythrobacteraceae.Erythrobacter	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Caryophanaceae	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Herpetosiphonales.Herpetosiphonaceae	0.0			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae.Leptotrichia	2.20295176684			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Micropruina	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermacoccaceae.Dermacoccus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae.Caulobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Peptococcus	0.110674438775			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcineae_incertae_sedis	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Acidaminococcus	0.962958161859			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Tsukamurellaceae.Tsukamurella	0.0			-
Bacteria.Chloroflexi.Caldilineae.Caldilineales.Caldilineaceae.Caldilinea	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Phascolarctobacterium	2.01055026121			0.00529991267452
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae	3.4104704812			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Methyloversatilis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dietziaceae.Dietzia	0.718034938178			-
Bacteria.Firmicutes.Bacilli.Bacillales.Sporolactobacillaceae.Tuberibacillus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Sporotalea	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast.Bangiophyceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Halomonadaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Comamonas	0.201247442107			-
Bacteria.Verrucomicrobia.Subdivision3.Subdivision3_genera_incertae_sedis	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Roseomonas	0.105784407345			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Spirochaetaceae.Treponema	2.0931859808			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Cellvibrio	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Craurococcus	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Sharpea	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Psychrobacter	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Singulisphaera	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Lactobacillus	3.410368286			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Shimazuella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria	2.56227021379			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae	1.34425869195			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales	2.09478659121			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Dyella	0.0			-
Bacteria.Verrucomicrobia	1.31709657295			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Sporocytophaga	0.0			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae.Thermovirga	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Stella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Clavibacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Acetobacter	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Thermales.Thermaceae.Meiothermus	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfuromonadales.Geobacteraceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Alphaproteobacteria_incertae_sedis.Novispirillum	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Sinobacteraceae.Steroidobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Brevibacteriaceae.Brevibacterium	0.319896866575			-
Bacteria.OP10.OP10_genera_incertae_sedis	0.0			-
Bacteria.Tenericutes.Mollicutes.Anaeroplasmatales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Neisseria	2.29885604166			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Pelomonas	1.28952286632			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Mitsuokella	0.342723569406			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Arcicella	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Isosphaera	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae.Microbispora	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae.Rikenella	0.0			-
Bacteria.Proteobacteria	2.85229486308			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae	0.551974865662			-
Bacteria.Bacteria_incertae_sedis	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae	0.0644649843845			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidaceae	3.61386204542	Low_O2	3.30026735669	3.03429396914e-07
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Micrococcus	1.44943349432			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Turicibacter	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Macrococcus	0.0			-
Bacteria.Verrucomicrobia.Opitutae.Puniceicoccales.Puniceicoccaceae	0.271175594734			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Microcella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales	1.64577726746			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae.Jonquetella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Paenibacillus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Succiniclasticum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cryptosporangiaceae.Cryptosporangium	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Rhodocyclus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Patulibacteraceae.Patulibacter	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Thermales.Thermaceae.Thermus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Herminiimonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylobacteriaceae	0.920221674495			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Planobacterium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV.Proteocatella	0.0			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Brachyspiraceae.Brachyspira	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Gracilibacteraceae.Gracilibacter	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Gemella	1.87433995357			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Brucellaceae	0.0			-
Bacteria.Tenericutes.Mollicutes.Mycoplasmatales.Mycoplasmataceae	1.23305193359			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Haemophilus	2.04338328599			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Millisia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Gluconobacter	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp9	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Denitratisoma	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Wautersia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Vogesella	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Vitellibacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Rhodopila	0.0			-
Archaea	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Nubsella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Acidisphaera	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.Anaplasmataceae	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp11	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae	0.946125868622			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiopsaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Schwartzia	0.760836517973			-
Bacteria.Chloroflexi.Chloroflexi.Chloroflexales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Marmoricola	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Herbaspirillum	0.0			-
Bacteria.Tenericutes.Mollicutes.Acholeplasmatales.Acholeplasmataceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Conexibacteraceae.Conexibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae.Sphaerisporangium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Parascardovia	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Anaerosphaera	0.0			-
Bacteria.Spirochaetes	2.57109148333			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae.Wolinella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Chromatiales.Chromatiaceae.Rheinheimera	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales	0.966681958121			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Sinobacteraceae.Nevskia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Morganella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Roseburia	2.19076699577			8.35869877247e-06
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae	1.34870452985			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Kaistella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Actinomyces	2.46433184605			-
Bacteria.Nitrospira.Nitrospira.Nitrospirales.Nitrospiraceae.Leptospirillum	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Runella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Nocardia	0.0			-
Bacteria.Bacteroidetes.Bacteroidetes_incertae_sedis.Prolixibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Lapillicoccus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Acetitomaculum	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Uruburuella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Beijerinckiaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria	1.81837575645			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Collinsella	0.183660967813			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Aeromonadaceae.Aeromonas	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Spirosoma	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Lactococcus	0.31218511198			-
Archaea.Euryarchaeota	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae	1.35527251282			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Simonsiella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Bifidobacterium	0.144487978587			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Catenuloplanes	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bacteriovoracaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Loktanella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Zymophilus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Curtobacterium	0.0			-
Bacteria.Bacteria_incertae_sedis.Ktedonobacteria	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIII.Anaerovorax	0.413077256951			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Butyrivibrio	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Moryella	1.07980622938			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae	0.421207288826			-
Bacteria.Chloroflexi.Anaerolineae.Anaerolineales.Anaerolineaceae.Levilinea	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Xanthobacteraceae.Labrys	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Nicoletella	0.0			-
Bacteria.Gemmatimonadetes.Gemmatimonadetes.Gemmatimonadales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Alysiella	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales.Deinococcaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Terrabacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Dialister	2.33986062258			-
Bacteria.Verrucomicrobia.Opitutae	0.290974425807			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Sanguibacteraceae.Sanguibacter	0.0			-
Bacteria.Firmicutes	3.75624929984	Mid_O2	3.20690963892	0.000254990131314
Bacteria.Acidobacteria.Acidobacteria_Gp6.Gp6	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Alphaproteobacteria_incertae_sedis	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Capnocytophaga	2.5404441165			-
Bacteria.Proteobacteria.Gammaproteobacteria.Chromatiales.Chromatiaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Listeriaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Nitriliruptorales.Nitriliruptoraceae.Nitriliruptor	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Pirellula	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Halobacillus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae	0.789550932292			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Phyllobacteriaceae.Phyllobacterium	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp7.Gp7	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Tsukamurellaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Planococcus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Lactonifactor	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Asaia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Psychromonadaceae.Psychromonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales	0.712012438059			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae.Lawsonia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Defluviicoccus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Pseudorhodoferax	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobulbaceae.Desulfobulbus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Simplicispira	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIII	0.734469882173			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermabacteraceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Cystobacteraceae.Cystobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Paraeggerthella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Enterorhabdus	0.0			-
Bacteria.Fibrobacteres.Fibrobacteria.Fibrobacterales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Sinobacteraceae	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Pedobacter	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae	2.36060653585			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Robinsoniella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Peptoniphilus	1.87900968867			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Ethanoligenens	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Listeriaceae.Listeria	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales	1.80686834171			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Beutenbergiaceae.Beutenbergia	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Haliangiaceae	0.0			-
Bacteria.Lentisphaerae.Lentisphaeria.Victivallales.Victivallaceae.Victivallis	1.00242817334			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.SAR11.Pelagibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cellulomonadaceae.Oerskovia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Tepidicella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermacoccaceae.Demetria	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Phyllobacteriaceae.Mesorhizobium	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Flavisolibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae	2.47041450547	Mid_O2	2.18920098451	4.09543736777e-05
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Polyangiaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Staphylococcus	3.09990452664	High_O2	2.78990872935	1.61097126215e-09
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Segetibacter	0.0			-
Bacteria.Aquificae.Aquificae.Aquificales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales	2.28115363703			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Beijerinckiaceae.Beijerinckia	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Myxococcaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Atopobium	2.11845576433			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Gallicola	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Leifsonia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Brachymonas	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Geodermatophilaceae.Geodermatophilus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales	2.58004554285			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Dehalobacter	0.0			-
Bacteria.Planctomycetes.Planctomycetacia	0.403490454449			-
Bacteria.Acidobacteria.Acidobacteria_Gp10.Gp10	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobidae_incertae_sedis.Ilumatobacter	0.0			-
Archaea.Euryarchaeota.Methanobacteria.Methanobacteriales.Methanobacteriaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Carnobacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Gardnerella	1.93188172158			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Nannocystaceae.Enhygromyxa	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Eubacterium	1.01030712208			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Agrococcus	0.0			-
Bacteria.Gemmatimonadetes	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Agromonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Enterobacter	0.613375407545			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Xanthobacteraceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria	0.582318399995			-
Archaea.Euryarchaeota.Methanobacteria.Methanobacteriales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Micromonospora	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Thermales.Thermaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Aquimonas	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Desulfonispora	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Bradyrhizobium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Salinibacterium	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_V.GpV	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Syntrophomonadaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales	2.44972444594			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bdellovibrionaceae	0.0			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae.Pyramidobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Iamiaceae.Iamia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Nitrosomonadales.Nitrosomonadaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Brucellaceae.Pseudochrobactrum	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Aggregatibacter	0.851770940819			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Francisellaceae.Francisella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIII.Mogibacterium	0.725199178876			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhizobiaceae.Kaistia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae	0.856777769462			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Fastidiosipila	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Rathayibacter	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast.Streptophyta	1.26494959258			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Acetanaerobacterium	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Oxalophagus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Methylococcales.Methylococcaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Castellaniella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Aneurinibacillus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Bosea	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Williamsia	0.0			-
Bacteria.Firmicutes.Erysipelotrichi	1.45115161006			1.96965919418e-05
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae	3.10658498178	High_O2	2.79725071577	1.76156078279e-08
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Barnesiella	1.60959585247			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Blastomonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales.Methylophilaceae.Methylotenera	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Alkanindiges	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales	0.294348499081			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Mycobacteriaceae	0.923077557053			-
Bacteria.Fibrobacteres.Fibrobacteria	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Methylococcales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Aquabacterium	0.21949133279			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Rhodanobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Amycolatopsis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales.Rubrobacteraceae.Rubrobacter	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfuromonadales.Geobacteraceae.Geobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Mannheimia	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Ammoniphilus	0.0			-
Bacteria.Nitrospira	0.0			-
Bacteria.Tenericutes.Mollicutes.Mycoplasmatales.Mycoplasmataceae.Ureaplasma	1.13139295368			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Proteus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Abiotrophia	1.02620903583			-
Bacteria.Proteobacteria.Gammaproteobacteria	2.49281699228			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI	2.23609707853			1.61000478861e-05
Bacteria.Actinobacteria.Actinobacteria	3.82686791902	High_O2	3.52571965976	4.14822868967e-09
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae	0.0284387618983			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Cystobacteraceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae	2.69512629034	Low_O2	2.38734733057	1.86328498211e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Sporobacter	0.540133110254	Low_O2	2.39886772371	0.00312178398861
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Erysipelothrix	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Parabacteroides	2.85745935002	Low_O2	2.56893797531	1.1878222933e-07
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cellulomonadaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Caldicellulosiruptor	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Catellicoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Thermoleophilales.Thermoleophilaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Pseudobutyrivibrio	0.369064205489			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Wohlfahrtiimonas	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Caryophanaceae.Caryophanon	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Halomonadaceae.Kushneria	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Actinoplanes	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Marinilactibacillus	0.0			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae	2.63142157707			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Selenomonas	1.69958221597			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Promicromonosporaceae.Cellulosimicrobium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Citrobacter	0.550151401869			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Enterococcus	0.292223878141			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast	1.27295723463			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Luteococcus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcineae_incertae_sedis.Demequina	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Akkermansia	1.26499742827			-
Bacteria.Aquificae.Aquificae.Aquificales.Hydrogenothermaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Eremococcus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Sporacetigenium	1.03423225946			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Vagococcus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales.Hydrogenophilaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Alicycliphilus	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp16.Gp16	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Oceanospirillaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Lactovum	0.0			-
Bacteria.Synergistetes.Synergistia.Synergistales	0.543036074883			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Arcanobacterium	0.0			-
Bacteria.TM7	1.77648926866			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Pectinatus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiopsaceae.Thermobifida	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Stenoxybacter	0.0741653389817			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales.Trueperaceae.Truepera	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Ideonella	0.0			-
Bacteria.Bacteria_incertae_sedis.Ktedonobacteria.Ktedonobacterales	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Cryomorphaceae.Fluviicola	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Thermomonas	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Kribbella	0.0			-
Bacteria.Fibrobacteres.Fibrobacteria.Fibrobacterales.Fibrobacteraceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae	1.60688281279			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Atopostipes	0.0			-
Bacteria.Verrucomicrobia.Spartobacteria	0.0			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Leptospiraceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV.Blautia	1.63505064999			4.31123688696e-06
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Zimmermannella	0.143748510711			-
Bacteria.Thermotogae.Thermotogae.Thermotogales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Tessaracoccus	0.0			-
Bacteria.Aquificae.Aquificae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_IX.GpIX	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Coprobacillus	0.772475386592	Low_O2	2.11927786999	5.66600286201e-05
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Pantoea	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV.Howardella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Lonepinella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales.Hydrogenophilaceae.Tepidiphilus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Thermomonosporaceae.Actinoallomurus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Azohydromonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Azospirillum	0.0			-
Bacteria.Tenericutes.Mollicutes.Anaeroplasmatales.Anaeroplasmataceae	0.0			-
Bacteria.Tenericutes.Mollicutes	1.2388333333			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfuromonadales.Desulfuromonadaceae	0.0			-
Bacteria.Fibrobacteres	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Thermomonosporaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Thermocrispum	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Verrucomicrobium	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Salinicoccus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Atopococcus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae	2.14026314772			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Alteromonadaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Kocuria	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Cupriavidus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Beutenbergiaceae.Salana	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Roseateles	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Sinobacteraceae.Hydrocarboniphaga	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae	1.10250190032			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Epilithonimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Ignatzschineria	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Kineosporiaceae.Quadrisphaera	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Porphyromonas	2.12645508843			-
Bacteria.Acidobacteria.Acidobacteria_Gp17.Gp17	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Cryptobacterium	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Cystobacteraceae.Anaeromyxobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Haematobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Tetrasphaera	0.0			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Leptospiraceae.Leptospira	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Beijerinckiaceae.Chelatococcus	0.0			-
Bacteria.Nitrospira.Nitrospira.Nitrospirales.Nitrospiraceae.Nitrospira	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Nitrosomonadales.Nitrosomonadaceae.Nitrosomonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Magnetospirillum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Corynebacteriaceae.Corynebacterium	3.1993232895	High_O2	2.88714295803	1.94485200196e-06
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.SAR11	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_II	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Facklamia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Erwinia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Janthinobacterium	0.187812391517			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Obesumbacterium	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Jeotgalicoccus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Anaerobacter	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae	1.20826912165			1.3621023627e-05
Bacteria.Acidobacteria.Holophagae.Holophagales.Holophagaceae.Geothrix	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales	3.83364499798	Low_O2	3.5047099051	8.73311066137e-07
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Salegentibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Agromyces	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Pedomicrobium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Solirubrobacteraceae	0.0			-
Bacteria.Chlamydiae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Conchiformibius	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Gemmata	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Gammaproteobacteria_incertae_sedis.Solimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Photorhabdus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Serratia	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Riemerella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Niastella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Citricoccus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Azomonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Tepidimonas	0.0			-
Bacteria.Thermotogae.Thermotogae.Thermotogales.Thermotogaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Rhodoferax	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Bulleidia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermatophilaceae	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_XIII.GpXIII	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_XIII	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Chloroflexales.Chloroflexaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales	2.6295092336			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Jonesiaceae	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Dysgonomonas	0.0			-
Bacteria.Aquificae	0.0			-
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales.Sphaerobacteraceae	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Odoribacter	1.6927061342			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Chitinimonas	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp3.Gp3	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Rhodopseudomonas	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Emticicia	0.0			-
Bacteria.Thermotogae.Thermotogae.Thermotogales.Thermotogaceae.Fervidobacterium	0.0			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Fusobacteriaceae	2.60147139376			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Myroides	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae	0.197761858518			-
Bacteria.Aquificae.Aquificae.Aquificales.Hydrogenothermaceae.Sulfurihydrogenibium	0.0			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales	2.91800924839			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae	0.393334161779			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Adhaeribacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae.Phenylobacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Alloscardovia	0.0			-
Bacteria.TM7.TM7_genera_incertae_sedis	1.77648926866			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae	2.50554974768			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Sarcina	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Faecalibacterium	2.72048499929	Low_O2	2.3363483989	5.51450208713e-07
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Yonghaparkia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Enhydrobacter	0.684346886888			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XVIII	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales	1.93705136418			-
Bacteria.Chloroflexi.Chloroflexi.Herpetosiphonales.Herpetosiphonaceae.Herpetosiphon	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Halomonadaceae.Halomonas	0.0			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Brachyspiraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Varibaculum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Xanthobacteraceae.Xanthobacter	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Holdemania	0.301107515886			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Haliangiaceae.Haliangium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Arsenophonus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales.Legionellaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Acinetobacter	1.90799512132			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Thiotrichaceae	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp1.Gp1	0.0			-
Bacteria.Firmicutes.Bacilli	3.66300526959	Mid_O2	3.32259237754	4.63129214751e-07
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Anaerosinus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Thermicanus	0.0			-
Bacteria.Lentisphaerae	1.30439735172			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfuromonadales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermacoccaceae.Kytococcus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Anaerofilum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Actinoalloteichus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae	1.11568945955			-
Bacteria.Verrucomicrobia.Opitutae.Puniceicoccales.Puniceicoccaceae.Coraliomargarita	0.260925889745			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Chitinophaga	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales	1.11926577451			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Parasutterella	1.85984418853			0.000480703577769
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Aurantimonadaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Veillonella	2.81423221923			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Novosphingobium	0.592998777489			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae	2.88901528988			-
Bacteria.Tenericutes	1.71451650861			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Oceanospirillaceae.Marinomonas	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales	0.108711910114			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Geodermatophilaceae.Blastococcus	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Filimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Burkholderia	0.14179409651			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Ramlibacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Duganella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Cardiobacteriales.Cardiobacteriaceae	0.965545760799			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidales_incertae_sedis.Phocaeicola	0.0			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae.Cloacibacillus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Conexibacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiopsaceae.Nocardiopsis	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae.Desulfovibrio	0.173990047237			-
Bacteria.Firmicutes.Clostridia.Clostridiales	3.39093818921	Low_O2	3.01400890255	2.11588168279e-06
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Kofleriaceae	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae	1.27010406948			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Saccharibacillus	0.0			-
Bacteria.Verrucomicrobia.Opitutae.Opitutales.Opitutaceae	0.0			-
Bacteria.OP10	0.0			-
Bacteria.Chloroflexi.Caldilineae.Caldilineales.Caldilineaceae	0.0			-
Bacteria.Gemmatimonadetes.Gemmatimonadetes.Gemmatimonadales.Gemmatimonadaceae.Gemmatimonas	0.0			-
Bacteria.Bacteroidetes.Flavobacteria	3.04481330312			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Ralstonia	0.626442496515			-
Bacteria.OP11	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae.Methylopila	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae	0.134429458973			-
Bacteria.Gemmatimonadetes.Gemmatimonadetes.Gemmatimonadales.Gemmatimonadaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Parvimonas	1.55213562396			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Gillisia	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Hallella	0.412593068451			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Megamonas	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae	0.209280977251			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Solirubrobacteraceae.Solirubrobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Geodermatophilaceae.Modestobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Actinopolymorpha	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Phocoenobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Pelotomaculum	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bacteriovoracaceae.Bacteriovorax	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Propionicicella	0.0			-
Archaea.Euryarchaeota.Methanobacteria	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Helcococcus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Silanimonas	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Frigoribacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Virgisporangium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Moraxella	1.7170197705			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Francisellaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Peptostreptococcus	0.613054178946			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Pseudoramibacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Dechloromonas	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Wautersiella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Bordetella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.Rickettsiaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales.Coxiellaceae	0.0			-
Bacteria.Tenericutes.Mollicutes.Anaeroplasmatales.Anaeroplasmataceae.Anaeroplasma	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Laceyella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Klebsiella	0.861153691002			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Hymenobacter	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Campylobacteraceae.Campylobacter	1.93269100942			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae.Nonomuraea	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Nesterenkonia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptomycetaceae.Streptomyces	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae.Asticcacaulis	0.0			-
Bacteria.Spirochaetes.Spirochaetes	2.57109148333			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Ottowia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Pseudonocardia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Aeromonadaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae.Brevundimonas	0.227487482289			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Prauserella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Jonesiaceae.Jonesia	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Polyangiaceae.Sorangium	0.0			-
Bacteria.Chloroflexi.Thermomicrobia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Stenotrophomonas	0.258863265629			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillales_incertae_sedis	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Thermales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Janibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Saccharomonospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Corynebacteriaceae.Turicella	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Allobaculum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales	0.718532336515			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Luteolibacter	0.0			-
Bacteria.Acidobacteria.Holophagae.Holophagales	0.0			-
Bacteria.Chlamydiae.Chlamydiae.Chlamydiales.Parachlamydiaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Catonella	1.37306196758			-
Bacteria.Verrucomicrobia.Opitutae.Opitutales.Opitutaceae.Opitutus	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_IV.GpIV	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Afipia	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales	0.403490454449			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Larkinella	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp22	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Nocardioides	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Shuttleworthia	0.171175659486			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XVII.Thermaerobacter	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Cloacibacterium	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Cryomorphaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Eggerthella	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Leuconostocaceae.Weissella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales.Methylophilaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Xanthobacteraceae.Ancylobacter	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Bavariicoccus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Succinivibrionaceae.Succinivibrio	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Pseudoalteromonadaceae.Pseudoalteromonas	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Propionibacterium	3.69700864091	High_O2	3.40063934744	1.03422819925e-09
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Promicromonosporaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Asaccharobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhizobiaceae	0.805971884939			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Zhouia	0.0			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Spirochaetaceae	2.09353556188			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales.Coxiellaceae.Aquicella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales	3.11667819702	High_O2	2.80726957244	1.74143017971e-08
Bacteria.Proteobacteria.Gammaproteobacteria.Vibrionales.Vibrionaceae.Photobacterium	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Achromobacter	0.0			-
Bacteria.Verrucomicrobia.Subdivision3	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Aerococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Brevibacillus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Lachnobacterium	0.0			-
Bacteria.Chloroflexi.Anaerolineae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae	0.0118018013031			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Catenibacterium	0.49183000249			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Nannocystaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales	1.99859449827			0.00206827787783
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Amaricoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Actinobaculum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nakamurellaceae.Humicoccus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Azospira	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Methylococcales.Methylococcaceae.Methylobacter	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Myxococcaceae.Myxococcus	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp16	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfomicrobiaceae.Desulfomicrobium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Psychromonadaceae	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae	1.57062614246			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Thermobacillus	0.0			-
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales.Sphaerobacteraceae.Sphaerobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Rhodobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae	0.285919796411			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae	3.69715538436	High_O2	3.40073512539	9.483488451e-10
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Alteromonadaceae.Marinobacter	0.0			-
Bacteria.Lentisphaerae.Lentisphaeria.Victivallales	1.00242817334			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Pigmentiphaga	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Friedmanniella	0.0			-
Bacteria.Bacteria_incertae_sedis.Ktedonobacteria.Ktedonobacterales.Ktedonobacteraceae.Ktedonobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Thiotrichaceae.Thiothrix	0.0			-
Bacteria.Bacteroidetes.Bacteroidia	4.20102935314	Low_O2	3.87801123731	6.57339680172e-07
Bacteria.Fibrobacteres.Fibrobacteria.Fibrobacterales.Fibrobacteraceae.Fibrobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Promicromonosporaceae.Isoptericola	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Terrimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Trabulsiella	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Flavobacterium	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Prevotella	2.80009989011			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Schlegelella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Planomicrobium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV	1.64386196044			7.01676836905e-06
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cyclobacteriaceae	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales	0.657675381978			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Solitalea	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Anaerofustis	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Kluyvera	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales	2.72026242362			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Syntrophococcus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Subdoligranulum	1.61343880163			1.10302381935e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV.Anaerovirgula	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Erythrobacteraceae.Porphyrobacter	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillales_incertae_sedis.Rummeliibacillus	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Tannerella	0.886379042122			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XII	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Nitrosomonadales	0.0			-
Bacteria.Lentisphaerae.Lentisphaeria.Victivallales.Victivallaceae	1.00242817334			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Thermoactinomyces	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Gelidibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Couchioplanes	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae	1.95293992671			3.28389218636e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Johnsonella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Rhodothermaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Dolosigranulum	2.34946525313			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Ruminococcus	2.2857755088			0.000426345827127
Bacteria.Cyanobacteria.Cyanobacteria.Family_I	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales	3.65550571119	Mid_O2	3.31452320331	5.8897479948e-08
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Chryseobacterium	0.412490267237			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Actinomycetospora	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Paracraurococcus	0.0			-
Bacteria.Tenericutes.Mollicutes.Acholeplasmatales.Acholeplasmataceae.Acholeplasma	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Geodermatophilaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobulbaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nakamurellaceae	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_V	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Oscillibacter	2.33206737418	Low_O2	2.08867932037	2.77785594999e-06
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Zoogloea	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Gordonibacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Erythrobacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Mycetocola	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Aeromicrobium	0.0			-
Bacteria.Chloroflexi.Anaerolineae.Anaerolineales.Anaerolineaceae.Longilinea	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Cardiobacteriales	1.26522643986			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Desemzia	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Rhodopirellula	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Gallibacterium	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales.Hydrogenophilaceae.Hydrogenophilus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Propionimicrobium	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Uliginosibacterium	0.0			-
Bacteria.Acidobacteria.Holophagae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Phyllobacteriaceae.Aminobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales.Rubrobacteraceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae	2.4708710268			-
Bacteria.Firmicutes.Bacilli.Bacillales.Listeriaceae.Brochothrix	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Arsenicicoccus	0.0			-
Bacteria.Chloroflexi.Anaerolineae.Anaerolineales	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidales_incertae_sedis	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Lacibacter	0.0			-
Bacteria.Chloroflexi.Anaerolineae.Anaerolineales.Anaerolineaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Shinella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Rahnella	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae	0.307767778115			-
Bacteria.Chloroflexi	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Lysobacter	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae.Alistipes	2.83812865942	Low_O2	2.57065979914	7.3522279302e-05
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae.Albibacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Bergeriella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae	2.91516683549			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermabacteraceae.Dermabacter	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_VIII	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Vibrionales.Vibrionaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhodobiaceae	0.0			-
Bacteria.Tenericutes.Mollicutes.Anaeroplasmatales.Anaeroplasmataceae.Asteroleplasma	0.0			-
Bacteria.Verrucomicrobia.Opitutae.Opitutales	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Blastobacter	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Herpetosiphonales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales.Hydrogenophilaceae.Petrobacter	0.0			-
Bacteria.Fusobacteria	3.39243257811			-
Bacteria.Firmicutes.Clostridia	3.39635326083	Low_O2	3.02092625581	2.11588168279e-06
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cellulomonadaceae.Cellulomonas	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Coprococcus	1.7766525744			6.42785203055e-06
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Saccharopolyspora	0.0			-
Bacteria.Chloroflexi.Caldilineae	0.0			-
Bacteria.Bacteroidetes.Bacteroidetes_incertae_sedis	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp5.Gp5	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae.Methylocystis	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Succinivibrionaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Cronobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Luteimonas	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Iamiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Olsenella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptomycetaceae	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Xylanibacter	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Cryomorphaceae.Crocinitomix	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Garciella	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Alkalibacterium	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Sporosarcina	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales	1.45115161006			1.96965919418e-05
Bacteria.Tenericutes.Mollicutes.Mycoplasmatales	1.53408192749			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Clostridium	0.711723828129			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales.Legionellaceae.Legionella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nakamurellaceae.Nakamurella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermabacteraceae.Brachybacterium	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Thermoanaerobacterium	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Tumebacillus	0.140700778873			-
Bacteria.Planctomycetes	0.403490454449			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Nosocomiicoccus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Oligella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Renibacterium	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Rhodothermaceae.Salinibacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Lampropedia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Brevibacteriaceae	0.319896866575			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Shewanellaceae.Shewanella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Derxia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Alteromonadaceae.Alishewanella	0.0			-
Bacteria.Acidobacteria	0.222580322495			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Cohnella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Ornithinimicrobium	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales.Trueperaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Salsuginibacillus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Gammaproteobacteria_incertae_sedis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Rothia	2.503294351			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sandaracinobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Thermomonosporaceae.Actinomadura	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Phycicoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Plantibacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Blastochloris	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_VIII.GpVIII	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Aquaspirillum	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Haloferula	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp11.Gp11	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bacteriovoracaceae.Peredibacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Filifactor	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Thermoleophilales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Jiangella	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Leuconostocaceae.Leuconostoc	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Paludibacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Megasphaera	1.60525278844			-
Bacteria.Proteobacteria.Gammaproteobacteria.Chromatiales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Azonexus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Belnapia	0.0507176791994			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Allisonella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Mobiluncus	0.514988020508			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_IV	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Malikia	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_IX	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales	1.57062614246			-
Bacteria.Actinobacteria.Actinobacteria.Nitriliruptorales.Nitriliruptoraceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Syntrophobacterales.Syntrophobacteraceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Kofleriaceae.Kofleria	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XVII	0.0			-
Archaea.Euryarchaeota.Methanobacteria.Methanobacteriales.Methanobacteriaceae.Methanobrevibacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Anaeroglobus	0.293717896111			-
Bacteria.Verrucomicrobia.Opitutae.Puniceicoccales	0.56711097488			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Campylobacteraceae.Arcobacter	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp9.Gp9	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Patulibacteraceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Massilia	0.523451795667			-
Bacteria.BRC1	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Pectobacterium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhizobiaceae.Ensifer	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Zavarzinella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Sporolactobacillaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Centipeda	0.58521041984			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylobacteriaceae.Microvirga	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Flexibacter	0.0			-
Bacteria.Fusobacteria.Fusobacteria	3.39243257811			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Sutterella	1.22555332621			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingobium	0.461021899267			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Anaerotruncus	0.690271511728			1.17863151969e-05
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobidae_incertae_sedis	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Saprospiraceae.Haliscomenobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Anaerosporobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Gluconacetobacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Hydrogenophaga	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Maritalea	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales.Methylophilaceae.Methylobacillus	0.0			-
Bacteria.Gemmatimonadetes.Gemmatimonadetes	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Polynucleobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Yersinia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis	0.631627622021			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Marvinbryantia	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Salirhabdus	0.0			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae.Sneathia	2.4049231321			-
Bacteria.Chloroflexi.Caldilineae.Caldilineales	0.0			-
Bacteria.Thermotogae	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Paraprevotella	2.01211343579			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Hespellia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Beutenbergiaceae	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Pontibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Gelria	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.Rickettsiaceae.Rickettsia	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XII.Fusibacter	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Solobacterium	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobacteraceae	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae	3.03954957424	Low_O2	2.72969643662	3.98313421073e-06
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Leptothrix	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Pseudoalteromonadaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Shewanellaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Mycobacteriaceae.Mycobacterium	0.923077557053			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Propionivibrio	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria	1.2944816118			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Yaniellaceae.Yaniella	0.0			-
Bacteria	3.99999810883			-
Bacteria.Actinobacteria	4.42661380317	High_O2	4.12559999656	4.14822868967e-09
